# -*- coding: utf-8 -*-
"""Group Project #2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBaFqV8PWnu7Boux4hzfWBH1GZp0J4P-
"""

# =====================================
# Scoring Parameters
# =====================================
# These values define how sequence similarity is evaluated.
# they directly correspond to the scoring scheme described in the writeup:
# *intended to be changed to the users preference*

DNAMatch = 2            # identical nucleotides
DNAMismatch = -1        # penalty for mismatched
gapOpen = -2            # penalty for introducing a gap
gapExtend = -1          # extensions at the end/beginning


# ====================================
# Rotation Search Parameters
# ====================================
# Parameters implement the "two pass search strategy" described in Problem 1:
# 1. Coarse search (first, larger steps)
# 2. Fine search (precise, small steps)
# *intended to be changed to the users preference*

roughPass = 7           # step size for coarse rotation search
threshold = 3           # stop coarse search if no improvement
finalThreshold = 1      # stricter stopping for fine search


# ====================================
# Needleman-Wunsch Global Alignment
# ====================================
# This function performs global alignment between two sequences.
# It uses dynamic programming to guarantee the optimal alignment.

def needlemanWunsch(seq1, seq2):
    # lengths of the sequences
    n = len(seq1)
    m = len(seq2)

    # Creating a scoring matrix (size: (n+1) x (m+1))
    # dp[i][j] represents best alignment score up to position i, j
    dp = [[0] * (m + 1) for _ in range(n + 1)]

    # Initialize first column (aligning seq1 with gaps)
    for i in range(1, n + 1):
        dp[i][0] = i * gapOpen
    # Initialize first row (aligning seq2 with gaps)
    for j in range(1, m + 1):
        dp[0][j] = j * gapOpen

    # Filling scoring matrix using recurrence relation
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            # Match or mismatch (diagonal move)
            match = dp[i-1][j-1] + (DNAMatch if seq1[i-1] == seq2[j-1] else DNAMismatch)
            # Gap in seq2 (vertical move)
            delete = dp[i-1][j] + gapOpen
            # Gap in seq1 (horizontal move)
            insert = dp[i][j-1] + gapOpen
            # Chooses best possible score
            dp[i][j] = max(match, delete, insert)

    # ====================================
    # Traceback to build aligned sequences
    # ====================================

    aligned1 = []
    aligned2 = []
    i, j = n, m

    # Walking backwards through matrix
    while i > 0 and j > 0:
        current = dp[i][j]
        diag = dp[i-1][j-1]
        up = dp[i-1][j]
        left = dp[i][j-1]
        # Diagonal (match or mismatch)
        if current == diag + (DNAMatch if seq1[i-1] == seq2[j-1] else DNAMismatch):
            aligned1.append(seq1[i-1])
            aligned2.append(seq2[j-1])
            i -= 1
            j -= 1
        # Gap in seq2
        elif current == up + gapOpen:
            aligned1.append(seq1[i-1])
            aligned2.append('-')
            i -= 1
        # Gap in seq1
        else:
            aligned1.append('-')
            aligned2.append(seq2[j-1])
            j -= 1

    # Adding remaining characters (if one sequence is longer)
    while i > 0:
        aligned1.append(seq1[i-1])
        aligned2.append('-')
        i -= 1

    while j > 0:
        aligned1.append('-')
        aligned2.append(seq2[j-1])
        j -= 1

    # Reverse sequences because traceback builds them backwards
    aligned1 = "".join(reversed(aligned1))
    aligned2 = "".join(reversed(aligned2))

    # Return aligned sequences and final score
    return aligned1, aligned2, dp[n][m]


# ===============================
# Circular Alignment
# ===============================
# This function implements the main idea of our project:
# correcting for circular breakpoint differences using rotation

def circularAlignment(seq1, seq2, roughPass, threshold, finalThreshold):

  # Initialize best score tracking
  highestScore = float('-inf')     # ensures anything run will be higher
  bestRotation = 0                 # index of best rotation
  bestAligned = None               # stores best alignment result
  noImprovementCount = 0           # used for early stopping

  # ==============================
  # First Pass: Coarse Search
  # ==============================
  # Rotating seq2 in larger steps to quickly find a good region

  for i in range(0, len(seq2), roughPass):
    # Rotate sequence (simulate different breakpoints)
    rotated = seq2[i:] + seq2[:i]
    # Align rotated sequence to reference
    a1, a2, score = needlemanWunsch(seq1, rotated)
    # Updating best alignment if improved
    if score > highestScore:
      highestScore = score
      bestRotation = i
      bestAligned = (a1, a2)
      noImprovementCount = 0
    else:
      noImprovementCount += 1
    # Early stopping if no improvement
    if noImprovementCount >= threshold:
      break

  # ========================
  # Second Pass: Fine Search
  # ========================
  # Searching more precisely around best rotation

  finalStart = max(0, bestRotation - roughPass)
  finalEnd = min(len(seq2), bestRotation + roughPass)
  noImprovementCount = 0

  for i in range(finalStart, finalEnd):

    rotated = seq2[i:] + seq2[:i]
    a1, a2, score = needlemanWunsch(seq1, rotated)

    if score > highestScore:
      highestScore = score
      bestRotation = i
      bestAligned = (a1, a2)
      noImprovementCount = 0
    else:
      noImprovementCount += 1

    if noImprovementCount >= finalThreshold:
      break

  # Safety fallback in case alignment was found
  if bestAligned is None:
    bestAligned = (seq1, seq2)

  return highestScore, bestRotation, bestAligned

# =============================
# Progressive Multiple Sequence Alignment
# =============================
# Building MSA by aligning sequences one at a time to a reference

def progressiveMSA(sequences):

  # First sequence acts as reference
  ref = sequences[0]
  msa = [ref]
  # Aligning each additional sequence
  for seq in sequences[1:]:

    score, rotation, (aligned_ref, aligned_seq) = circularAlignment(ref,
    seq, roughPass, threshold, finalThreshold)

    # Update reference to include gaps
    ref = aligned_ref

    # Update existing MSA sequences to match new gaps
    new_msa = []

    for old_seq in msa:
        new_seq = ""
        idx = 0

        for c in aligned_ref:
          if c == '-':
            new_seq += '-'
          else:
            if idx < len(old_seq):
                  new_seq += old_seq[idx]
                  idx += 1
            else:
              new_seq += '-'

        new_msa.append(new_seq)

    msa = new_msa

    # adding a newly aligned sequence
    msa.append(aligned_seq)

  return msa


# =============================
# Identity Function
# =============================
# Computing percentage similarity between to aligned sequences
# Ignores gaps to focus on true biological similarity

def identity(sequence1, sequence2):

  matches = 0
  length = 0

  for x, y in zip(sequence1, sequence2):
    if x == "-" or y == "-":
      continue

    length += 1

    if x == y:
      matches += 1

  if length == 0:
    return 0

  return (matches/length) * 100

# ==================
# Output Function
# ===================
# Displays Final alignment and identity score

def printMSA(msa):

    print("Final Multiple Sequence Alignment:\n")

    for i, seq in enumerate(msa):
        print(f"Sequence {i+1}: {seq}")

    identityPercentage = identity(msa[0], msa[1])
    print(f"\nIdentity Percentage: {identityPercentage:.2f}%")

# ==================
# Test Run
# ==================

sequence1 = "AAGGTATGGAGACCCCCATCAGTACCACCCAATGGATCCCTCCGACTGGACTTGGATTAGTGGGACCCAC"
sequence2 = "GTAGATGCCCAAAGGTATGGAGACCGGACTGACTTGAGGTAATAGTTGCTATTCAT"

sequences = [sequence1, sequence2]

msa_result = progressiveMSA(sequences)

printMSA(msa_result)

